[package]
name = "liballoc"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2021"

[dependencies.no-std-compat2]
path = "../../"
features = [ "alloc" ]

[features]
std = [ "no-std-compat2/std" ]
compat_hash = [ "no-std-compat2/compat_hash" ]
